@extends('web.templet.master')

{{-- @include('web.include.seo') --}}

@section('seo')
  <meta name="description" content="Credence">
@endsection

@section('content')
<section class="main-container col2-left-layout">
   <div class="container returnAndReplacement">
      <h2 class="text-center">Credence Terms of Use</h2>
        <hr>
      <p>This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures. <br>
         This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domainname [www.credenceever.com][www.credenceever.com] (“Website”), including the related mobile site and mobile application (hereinafter referred to as “Platform”) </p>

      <p>The Platform is owned by CredenceEver LLP a company incorporated under the Companies Act, 1956 with its registered office at #01, Mulagabharu Path,Hatigaon RoadGuwahati – 781006, Assam, India (hereinafter referred to as "Credence"). <br>
         Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with CredenceEver LLP and these terms and conditions including the policies constitute Your binding obligations, with Credence. <br>
         For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. Credence allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean Credence Internet Private Limited.
      </p>   
       
       <p>When You use any of the services provided by Us through the Platform, including but not limited to, (e.g. Product Reviews, Seller Reviews), You will be subject to the rules, guidelines, policies, terms, and conditions applicable to such service, and they shall be deemed to be incorporated into this Terms of Use and shall be considered as part and parcel of this Terms of Use. We reserve the right, at Our sole discretion, to change, modify, add or remove portions of these Terms of Use, at any time without any prior written notice to You. It is Your responsibility to review these Terms of Use periodically for updates / changes. Your continued use of the Platform following the posting of changes will mean that You accept and agree to the revisions. As long as You comply with these Terms of Use, We grant You a personal, non-exclusive, non-transferable, limited privilege to enter and use the Platform. <br>
          ACCESSING, BROWSING OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Credence Policies ((including but not limited to Privacy Policy available at Privacy) as amended from time to time.
       </p>

       <h4>Membership Eligibility</h4>
       <p>Transaction on the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents etc. are not eligible to use the Platform. If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and prior consent/ permission of a parent orlegal guardian.</p>
       <p>As a minor if you wish to transact on the Platform, such transaction on the Platform may be made by your legal guardian or parents. Credence reserves the right to terminate your membership and / or refuse to provide you with access to the Platform if it is brought to Credence's notice or if it is discovered that You are under the age of 18 years and transacting on the Platform. </p>

       <h4>Your Account and Registration Obligations</h4>
       <p>If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with the this Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform and refuse to provide You with access to the Platform.</p>
       <p>Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Platform. It is your responsibility to ensure that Your mobile phone number and your email address is always up to date on the Platform. You agree to notify Us promptly if your mobile phone number or e-mail address changes by updating the same on the Platform through a onetime password verification.</p>
       <p>You agree that Credence shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your Account in cases, including, where You have failed to update Your revised mobile phone number and/or e-mail address on the Website Platform.</p>
       <p>If You share or allow others to have access to Your account on the Platform (“Account”), by creating separate profiles under Your Account, or otherwise, they will be able to view and access Your Account information. You shall be solely liable and responsible for all the activities undertaken under Your Account, and any consequences therefrom.</p>

       <h4>Communications</h4>
       <p>When You use the Platform or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.</p>
       <p>Disclaimer: Pricing on any product(s) as is reflected on the Platform may be incorrectly reflected due to some technical issue, typographical error or product information published and in such an event Credence may cancel such your order(s).</p>

       <ol>
          <li>
            <p>You release and indemnify Credence and/or any of its officers and representatives from any cost, damage, liability, or other consequence of any of the actions of the Users of the Platform and specifically waive any claims that you may have in this behalf under any applicable law. Notwithstanding its reasonable efforts in that behalf, Credence cannot take responsibility or control the information provided by other Users which is made available on the Platform. You may find other User's information to be offensive, harmful, inconsistent, inaccurate, or deceptive. Please use caution and practice safe trading when using the Platform.</p>
          </li>
       </ol>

       <h4>Charges</h4>
       <p>Membership on the Platform is free for buyers. Credence does not charge any fee for browsing and buying on the Platform. Credence reserves the right to change its Fee Policy from time to time. In particular, Credence may at its sole discretion introduce new services and modify some or all of the existing services offered on the Platform. In such an event Credence reserves the right to introduce fees for the new services offered or amend/introduce fees for existing services, as the case may be. Changes to the Fee Policy shall be posted on the Platform and such changes shall automatically become effective immediately after they are posted on the Platform. Unless otherwise stated, all fees shall be quoted in Indian Rupees. You shall be solely responsible for compliance of all applicable laws including those in India for making payments to CredenceEver LLP.</p>

       <h4>Use of the Platform</h4>
       <p>You agree, undertake and confirm that Your use of Platform shall be strictly governed by the following binding principles:</p>
       <ol>
          <li>
             <p>You shall not use or share any information which:</p>
          </li>
       </ol>
       <p>(a) belongs to another person and to which You do not have any right to;</p>
       <p>(b) is grossly harmful, harassing, blasphemous, defamatory, obscene, pornographic, paedophilic, libellous, invasive of another's privacy, hateful, or racially, ethnically objectionable, disparaging, relating or encouraging money laundering or gambling, or otherwise unlawful in any manner whatever; or unlawfully threatening or unlawfully harassing including but not limited to "indecent representation of women" within the meaning of the Indecent Representation of Women (Prohibition) Act, 1986;</p>
       <p>(c) is misleading in any way;</p>
       <p>(d) is patently offensive to the online community, such as sexually explicit content, or content that promotes obscenity, paedophilia, racism, bigotry, hatred or physical harm of any kind against any group or individual;</p>
       <p>(e) harasses or advocates harassment of another person;</p>
       <p>(f) involves the transmission of "junk mail", "chain letters", or unsolicited mass mailing or "spamming";</p>
       <p>(g) promotes illegal activities or conduct that is abusive, threatening, obscene, defamatory or libellous;</p>
       <p>(h) infringes upon or violates any third party's rights [including, but not limited to, intellectual property rights, rights of privacy (including without limitation unauthorized disclosure of a person's name, email address, physical address or phone number) or rights of publicity];</p>
       <p>(i) promotes an illegal or unauthorized copy of another person's copyrighted work such as providing pirated computer programs or links to them, providing information to circumvent manufacture-installed copy-protect devices, or providing pirated music or links to pirated music files;</p>
       <p>(j) contains restricted or password-only access pages, or hidden pages or images (those not linked to or from another accessible page);</p>
       <p>(k) provides material that exploits people in a sexual, violent or otherwise inappropriate manner or solicits personal information from anyone;</p>
       <p>(l) provides instructional information about illegal activities such as making or buying illegal weapons, violating someone's privacy, or providing or creating computer viruses;</p>
       <p>(m) contains video, photographs, or images of another person (with a minor or an adult).</p>
       <p>(n) tries to gain unauthorized access or exceeds the scope of authorized access to the Platform or to profiles, blogs, communities, account information, bulletins, friend request, or other areas of the Platform or solicits passwords or personal identifying information for commercial or unlawful purposes from other users;</p>
       <p>(o) engages in commercial activities and/or sales without Our prior written consent such as contests, sweepstakes, barter, advertising and pyramid schemes, or the buying or selling of "virtual" products related to the Platform. Throughout this Terms of Use, Credence's prior written consent means a communication coming from Credence's Legal Department, specifically in response to Your request, and specifically addressing the activity or conduct for which You seek authorization;</p>
       <p>(p) solicits gambling or engages in any gambling activity which We, in Our sole discretion, believes is or could be construed as being illegal;</p>
       <p>(q) interferes with another USER's use and enjoyment of the Platform or any other individual's User and enjoyment of similar services;</p>
       <p>(r) refers to any Platform or URL that, in Our sole discretion, contains material that is inappropriate for the Platform or any other Platform, contains content that would be prohibited or violates the letter or spirit of these Terms of Use.</p>
       <p>(s) harm minors in any way;</p>
       <p>(t) infringes any patent, trademark, copyright or other proprietary rights or third party's trade secrets or rights of publicity or privacy or shall not be fraudulent or involve the sale of counterfeit or stolen products;</p>
       <p>(u) violates any law for the time being in force;</p>
       <p>(v) deceives or misleads the addressee/ users about the origin of such messages or communicates any information which is grossly offensive or menacing in nature;</p>
       <p>(w) impersonate another person;</p>
       <p>(x) contains software viruses or any other computer code, files or programs designed to interrupt, destroy or limit the functionality of any computer resource; or contains any trojan horses, worms, time bombs, cancelbots, easter eggs or other computer programming routines that may damage, detrimentally interfere with, diminish value of, surreptitiously intercept or expropriate any system, data or personal information;</p>
       <p>(y) threatens the unity, integrity, defence, security or sovereignty of India, friendly relations with foreign states, or public order or causes incitement to the commission of any cognizable offence or prevents investigation of any offence or is insulting any other nation.</p>
       <p>(z) shall not be false, inaccurate or misleading;</p>
       
       <ol>
          <li>
             <p>You shall not use any "deep-link", "page-scrape", "robot", "spider" or other automatic device, program, algorithm or methodology, or any similar or equivalent manual process, to access, acquire, copy or monitor any portion of the Platform or any Content, or in any way reproduce or circumvent the navigational structure or presentation of the Platform or any Content, to obtain or attempt to obtain any materials, documents or information through any means not purposely made available through the Platform. We reserve Our right to bar any such activity.</p>
          </li>
          <li>
             <p>You shall not attempt to gain unauthorized access to any portion or feature of the Platform, or any other systems or networks connected to the Platform or to any server, computer, network, or to any of the services offered on or through the Platform, by hacking, password "mining" or any other illegitimate means.</p>
          </li>
          <li>
             <p>You shall not probe, scan or test the vulnerability of the Platform or any network connected to the Platform nor breach the security or authentication measures on the Platform or any network connected to the Platform. You may not reverse look-up, trace or seek to trace any information on any other User of or visitor to Platform, or any other customer, including any account on the Platform not owned by You, to its source, or exploit the Platform or any service or information made available or offered by or through the Platform, in any way where the purpose is to reveal any information, including but not limited to personal identification or information, other than Your own information, as provided for by the Platform.</p>
          </li>
          <li>
             <p>You shall not make any negative, denigrating or defamatory statement(s) or comment(s) about Us or the brand name or domain name used by Us including the terms Credence, Credence.com, or otherwise engage in any conduct or action that might tarnish the image or reputation, of Credence on platform or otherwise tarnish or dilute any Credence's trade or service marks, trade name and/or goodwill associated with such trade or service marks, trade name as may be owned or used by us. You agree that You will not take any action that imposes an unreasonable or disproportionately large load on the infrastructure of the Platform or Credence's systems or networks, or any systems or networks connected to Credence.</p>
          </li>
          <li>
             <p>You agree not to use any device, software or routine to interfere or attempt to interfere with the proper working of the Platform or any transaction being conducted on the Platform, or with any other person's use of the Platform.</p>
          </li>
          <li>
            <p>You may not forge headers or otherwise manipulate identifiers in order to disguise the origin of any message or transmittal You send to Us on or through the Platform or any service offered on or through the Platform. You may not pretend that You are, or that You represent, someone else, or impersonate any other individual or entity.</p>
          </li>
          <li>
             <p>You may not use the Platform or any content for any purpose that is unlawful or prohibited by these Terms of Use, or to solicit the performance of any illegal activity or other activity which infringes the rights of Credence and / or others.</p>
          </li>
          <li>
            <p>You shall at all times ensure full compliance with the applicable provisions of the Information Technology Act, 2000 and rules thereunder as applicable and as amended from time to time and also all applicable Domestic laws, rules and regulations (including the provisions of any applicable Exchange Control Laws or Regulations in Force) and International Laws, Foreign Exchange Laws, Statutes, Ordinances and Regulations (including, but not limited to Sales Tax/VAT, Income Tax, Octroi, Service Tax, Central Excise, Custom Duty, Local Levies) regarding Your use of Our service and Your listing, purchase, solicitation of offers to purchase, and sale of products or services. You shall not engage in any transaction in an item or service, which is prohibited by the provisions of any applicable law including exchange control laws or regulations for the time being in force.</p>
          </li>
          <li>
             <p>Solely to enable Us to use the information You supply Us with, so that we are not violating any rights You might have in Your Information, You agree to grant Us a non-exclusive, worldwide, perpetual, irrevocable, royalty-free, sub-licensable (through multiple tiers) right to exercise the copyright, publicity, database rights or any other rights You have in Your Information, in any media now known or not currently known, with respect to Your Information. We will only use Your information in accordance with the Terms of Use and Privacy Policy applicable to use of the Platform.</p>
          </li>
          <li>
             <p>You shall not engage in advertising to, or solicitation of, other Users of the Platform to buy or sell any products or services, including, but not limited to, products or services related to that being displayed on the Platform or related to us. You may not transmit any chain letters or unsolicited commercial or junk email to other Users via the Platform. It shall be a violation of these Terms of Use to use any information obtained from the Platform in order to harass, abuse, or harm another person, or in order to contact, advertise to, solicit, or sell to another person other than Us without Our prior explicit consent. In order to protect Our Users from such advertising or solicitation, We reserve the right to restrict the number of messages or emails which a user may send to other Users in any 24-hour period which We deems appropriate in its sole discretion. You understand that We have the right at all times to disclose any information (including the identity of the persons providing information or materials on the Platform) as necessary to satisfy any law, regulation or valid governmental request. This may include, without limitation, disclosure of the information in connection with investigation of alleged illegal activity or solicitation of illegal activity or in response to a lawful court order or subpoena. In addition, We can (and You hereby expressly authorize Us to) disclose any information about You to law enforcement or other government officials, as we, in Our sole discretion, believe necessary or appropriate in connection with the investigation and/or resolution of possible crimes, especially those that may involve personal injury.</p>
          </li>
       </ol>
       <p>We reserve the right, but has no obligation, to monitor the materials posted on the Platform. Credence shall have the right to remove or edit any content that in its sole discretion violates, or is alleged to violate, any applicable law or either the spirit or letter of these Terms of Use. Notwithstanding this right, YOU REMAIN SOLELY RESPONSIBLE FOR THE CONTENT OF THE MATERIALS YOU POST ON THE PLATFORM AND IN YOUR PRIVATE MESSAGES. Please be advised that such Content posted does not necessarily reflect Credence views. In no event shall Credence assume or have any responsibility or liability for any Content posted or for any claims, damages or losses resulting from use of Content and/or appearance of Content on the Platform. You hereby represent and warrant that You have all necessary rights in and to all Content which You provide and all information it contains and that such Content shall not infringe any proprietary or other rights of third parties or contain any libelous, tortious, or otherwise unlawful information.</p>
       
       <ol>
          <li><p>It is possible that other users (including unauthorized users or "hackers") may post or transmit offensive or obscene materials on the Platform and that You may be involuntarily exposed to such offensive and obscene materials. It also is possible for others to obtain personal information about You due to your use of the Platform, and that the recipient may use such information to harass or injure You. We do not approve of such unauthorized uses, but by using the Platform You acknowledge and agree that We are not responsible for the use of any personal information that You publicly disclose or share with others on the Platform. Please carefully select the type of information that You publicly disclose or share with others on the Platform.</p> </li>
          <li><p>Credence shall have all the rights to take necessary action and claim damages that may occur due to your involvement/participation in any way on your own or through group/s of people, intentionally or unintentionally in DoS/DDoS (Distributed Denial of Services).</p></li>
          <li><p>If you choose to browse or transact on the Platform using the voice command-based shoppingfeature, you acknowledge that Credence and/or its affiliates will collect, store and use your voice inputs on this feature to customize your experience and provide additional functionality as well as to improve Credence’s and/or its affiliates’ products and services. Credence’s and/or its affiliates’ use of your voice data will be in accordance with the Credence Privacy Policy. You accept that your use of this feature is restricted to the territory of the Republic of India. This feature may not be accessible on certain devices and requires an internet connection. Credence reserves the right to change, enhance, suspend, or discontinue this feature, or any part of it, at any time without notice to you. Your continued use of this feature constitutes your acceptance of the terms related to this feature.</p></li>
       </ol>
       
       <h4>Contents Posted on Platform</h4>
       <p>Except as expressly provided in these Terms of Use, no part of the Platform and no Content may be copied, reproduced, republished, uploaded, posted, publicly displayed, encoded, translated, transmitted, or distributed in any way (including "mirroring") to any other computer, server, Platform or other medium for publication or distribution or for any commercial enterprise, without Credence's express prior written consent.</p>
       <p>You may use information on the products and services purposely made available on the Platform for downloading, provided that You (1) do not remove any proprietary notice language in all copies of such documents, (2) use such information only for your personal, non-commercial informational purpose and do not copy or post such information on any networked computer or broadcast it in any media, (3) make no modifications to any such information, and (4) do not make any additional representations or warranties relating to such documents.</p>
       <p>You shall be responsible for any notes, messages, emails, reviews, ratings, billboard postings, photos, drawings, profiles, opinions, ideas, images, videos, audio files or other materials or information posted or transmitted to the Platform (collectively, "Content"). Such Content will become Our property and You grant Us the worldwide, perpetual and transferable rights in such Content. We shall be entitled to, consistent with Our Privacy Policy as adopted in accordance with applicable law, use the Content or any of its elements for any type of use forever, including but not limited to promotional and advertising purposes and in any media whether now known or hereafter devised, including the creation of derivative works that may include the Content You provide. You agree that any Content You post may be used by us, consistent with Our Privacy Policy and Rules of Conduct on Site as mentioned herein, and You are not entitled to any payment or other compensation for such use.</p>
       <p>SOME CONTENT OFFERED ON THE PLATFORM MAY NOT BE SUITABLE FOR SOME VIEWERS AND THEREFORE VIEWER DISCRETION IS ADVISED. ALSO, SOME CONTENT OFFERED ON THE PLATFORM MAY NOT BE APPROPRIATE FOR VIEWERSHIP BY CHILDREN. PARENTS AND/OR LEGAL GUARDIANS ARE ADVISED TO EXERCISE DISCRETION BEFORE ALLOWING THEIR CHILDREN AND/OR WARDS TO ACCESS CONTENT ON THE PLATFORM.</p>
       
       <h4>Privacy</h4>
       <p>We view protection of Your privacy as a very important principle. We understand clearly that You and Your Personal Information is one of Our most important assets. We store and process Your Information including any sensitive financial information collected (as defined under the Information Technology Act, 2000), if any, on computers that may be protected by physical as well as reasonable technological security measures and procedures in accordance with Information Technology Act 2000 and Rules there under.Our current Privacy Policy is available at Privacy. Our current Privacy Policy is available at Privacy. If You object to Your Information being transferred or used in this way please do not use Platform. </p>
       <p>We may share personal information with our other corporate entities and affiliates. These entities and affiliatesmay market to you as a result of such sharing unless you explicitly opt-out.</p>
       <p>We may disclose personal information to third parties. This disclosure may be required for us to provide youaccess to our Services, to comply with our legal obligations, to enforce our User Agreement, to facilitate our marketing and advertising activities, or to prevent, detect, mitigate, and investigate fraudulent or illegal activities related to our Services. We do not disclose your personal information to third parties for their marketing and advertising purposes without your explicit consent.</p>
       <p>We may disclose personal information if required to do so by law or in the good faith belief that such disclosure is reasonably necessary to respond to subpoenas, court orders, or other legal process. We may disclose personal information to law enforcement offices, third party rights owners, or others in the good faith belief that such disclosure is reasonably necessary to: enforce our Terms or Privacy Policy; respond to claims that an advertisement, posting or other content violates the rights of a third party; or protect the rights, property or personal safety of our users or the general public.</p>
       <p>We and our affiliates will share / sell some or all of your personal information with another business entity should we (or our assets) plan to merge with, or be acquired by that business entity, or re-organization, amalgamation, restructuring of business. Should such a transaction occur that other business entity (or the new combined entity) will be required to follow this privacy policy with respect to your personal information.</p>
       
       <h4>Disclaimer of Warranties and Liability</h4>
       <p>This Platform, all the materials and products (including but not limited to software) and services, included on or otherwise made available to You through this site are provided on "as is" and "as available" basis without any representation or warranties, express or implied except otherwise specified in writing. Without prejudice to the forgoing paragraph, Credence does not warrant that:</p>
       <p>This Platform will be constantly available, or available at all; or</p>
       <p>The information on this Platform is complete, true, accurate or non-misleading.</p>
       <p>Credence will not be liable to You in any way or in relation to the Contents of, or use of, or otherwise in connection with, the Platform. Credence does not warrant that this site; information, Content, materials, product (including software) or services included on or otherwise made available to You through the Platform; their servers; or electronic communication sent from Us are free of viruses or other harmful components.</p>
       <p>Nothing on Platform constitutes, or is meant to constitute, advice of any kind. All the Products sold on Platform are governed by different state laws and if Weare unable to deliver such Products due to implications of different state laws, We will return or will give credit for the amount (if any) received in advance from the sale of such Product that could not be delivered to You.</p>
       <p>You will be required to enter a valid phone number while placing an order on the Platform. By registering Your phone number with us, You consent to be contacted by Us via phone calls, SMS notifications, mobile applications and/or any other electronic mode of communication in case of any order or shipment or delivery related updates. We will not use your personal information to initiate any promotional phone calls or SMS.</p>
       <p></p>
       
       <h4>Payment</h4>
       <p>While availing any of the payment method/s available on the Platform, we will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to:</p>
        <ol>
           <li><p>Lack of authorization for any transaction/s, or</p></li>
           <li><p>Exceeding the preset limit mutually agreed by You and between "Bank/s", or</p></li>
           <li><p>Any payment issues arising out of the transaction, or</p></li>
           <li><p>Decline of transaction for any other reason/s</p></li>
        </ol>
       <p>All payments made against the purchases/services on Platform by you shall be compulsorily in Indian Rupees acceptable in the Republic of India. Platform will not facilitate transaction with respect to any other form of currency with respect to the purchases made on Platform.</p>
       <p>Before shipping / delivering your order to you, We may request you to provide supporting documents (including but not limited to Govt. issued ID and address proof) to establish the ownership of the payment instrument used by you for your purchase. This is done in the interest of providing a safe online shopping environment to Our Users.</p>
       <p>Further:</p>
       <ol>
         <li><p>You have specifically authorized Credence or its service providers to collect, process, facilitate and remit payments and / or the Transaction Price electronically or through Cash on Delivery to and from other Users in respect of transactions through Payment Facility. </p></li>
         <li><p>You understand, accept and agree that the payment facility provided by Credence is neither a banking nor financial service but is merely a facilitator providing an electronic, automated online electronic payment, receiving payment through Cash On Delivery, collection and remittance facility for the Transactions on the Credence Platform using the existing authorized banking infrastructure and Credit Card payment gateway networks. Further, by providing Payment Facility.</p></li>
       </ol>
       <h4>Payment Facility for Buyers:</h4>
       <ol>
        <li><p>You, as a Buyer, understand that upon initiating a Transaction You are entering into a legally binding and enforceable contract with the Credence to purchase the products and /or services using the Payment Facility, and You shall pay the Transaction Price through Your Issuing Bank using Payment Facility.</p></li>
        <li><p>You, as a Buyer, may agree through electronic communication and electronic records and using the automated features as may be provided by Payment Facility on any extension / increase in the Dispatch and/or Delivery time and the Transaction shall stand amended to such extent. Any such extension / increase of Dispatch / Delivery time or subsequent modification / variation of the Transaction should be in compliance with Payment Facility Rules and Policies.</p></li>
        <li><p>You, as a Buyer, shall electronically notify Payment Facility using the appropriate Credence Platform features immediately upon Delivery or non Delivery within the time period as provided in Policies. Non notification by You of Delivery or non Delivery within the time period specified in the Policies shall be construed as a deemed Delivery in respect of that Transaction. In case of Cash On Delivery transactions, Buyer is not required to confirm the receipt of products or services.</p></li>
        <li><p>You, as a Buyer, shall be entitled to claim a refund of the Transaction Price (as Your sole and exclusive remedy) in case You do not receive the Delivery within the time period agreed in the Transaction or within the time period as provided in the Policies, whichever is earlier. In case you do not raise a refund claim using Platform features within the stipulated time than this would make You ineligible for a refund.</p></li>
        <li><p>You, as a Buyer, understand that the Payment Facility may not be available in full or in part for certain category of products and/or services and/or Transactions as mentioned in the Policies and hence You may not be entitled to a refund in respect of the Transactions for those products and /or services</p></li>
        <li><p>Except for Cash On Delivery transaction, refund, if any, shall be made at the same Issuing Bank from where Transaction Price was received, or through any other method available on the Platform, as chosen by You.</p></li>
        <li><p>For Cash On Delivery transactions, refunds, if any, will be made via electronic payment transfers.</p></li>
        <li><p>Refund shall be made in Indian Rupees only and shall be equivalent to the Transaction Price received in Indian Rupees.</p></li>
        <li><p>For electronics payments, refund shall be made through payment facility using NEFT / RTGS or any other online banking / electronic funds transfer system approved by Reserve Bank India (RBI).</p></li>
        <li><p>Refunds may be supported for select banks. Where a bank is not supported for processing refunds, You will be required to share alternate bank account details with us for processing the refund.</p></li>
        <li><p>Refund shall be conditional and shall be with recourse available to Credence in case of any misuse by Buyer.</p></li>
        <li><p>We may also request you for additional documents for verification.</p></li>
        <li><p>Refund shall be subject to Buyer complying with Policies.</p></li>
        <li><p>Credence reserves the right to impose limits on the number of Transactions or Transaction Price which Credence may receive from on an individual Valid Credit/Debit/ Cash Card / Valid Bank Account/ and such other infrastructure or any other financial instrument directly or indirectly through payment aggregator or through any such facility authorized by Reserve Bank of India to provide enabling support facility for collection and remittance of payment or by an individual Buyer during any time period, and reserves the right to refuse to process Transactions exceeding such limit.</p></li>
        <li><p>Credence reserves the right to refuse to process Transactions by Buyers with a prior history of questionable charges including without limitation breach of any agreements by Buyer with Credence or breach/violation of any law or any charges imposed by Issuing Bank or breach of any policy.</p></li>
        <li><p>Credence may do such checks as it deems fit before approving the receipt of/Buyers commitment to pay (for Cash On Delivery transactions) Transaction Price from the Buyer for security or other reasons at the discretion of Credence. As a result of such check if Credence is not satisfied with the creditability of the Buyer or genuineness of the Transaction or other reasons at its sole discretion, Credence shall have the right to reject the receipt of / Buyers commitment to pay Transaction Price. For avoidance of doubt, it is hereby clarified that the ‘Cash on Delivery’ feature for payment, may be disabled for certain account users, at the sole discretion of Credence.</p></li>
        <li><p>Credence may delay notifying the payment confirmation if Credence deems suspicious or for Buyers conducting high transaction volumes to ensure safety of the Transaction and Transaction Price. In addition, Credence may hold Transaction Price or remit Transaction Price to law enforcement officials (instead of refunding the same to Buyer) at the request of law enforcement officials or in the event the Buyer is engaged in any form of illegal activity.</p></li>
        <li><p>The Buyer acknowledges that Credence will not be liable for any damages, interests or claims etc. resulting from not processing a Transaction/Transaction Price or any delay in processing a Transaction/Transaction Price which is beyond control of Credence.</p></li>
       </ol>

       <h4>Compliance with Laws:</h4>
       <ol>
        <li><p>1.	As required by applicable law, if the Customer makes a purchase of an amount equal to or above INR 2 00 000.00, the Customer will be required to upload a scanned copy of his/her PAN card on the Platform, within 4 days of making the purchase, failing which, the purchase made by the Customer will be cancelled. The requirement to submit the PAN card arises only once and if it has been submitted once by the Customer, it need not be submitted again. The order of the Customer shall stand cancelled if there is a discrepancy between the name of the Customer and the name on the PAN Card.</p></li>
        <li><p>2.	Buyer shall comply with all the applicable laws (including without limitation Foreign Exchange Management Act, 1999 and the rules made and notifications issued there under and the Exchange Control Manual as may be issued by Reserve Bank of India from time to time, Customs Act, Information and Technology Act, 2000 as amended by the Information Technology (Amendment) Act 2008, Prevention of Money Laundering Act, 2002 and the rules made there under, Foreign Contribution Regulation Act, 1976 and the rules made there under, Income Tax Act, 1961 and the rules made there under, Export Import Policy of government of India) applicable to them respectively for using Payment Facility and Credence Platform.</p></li>
       </ol>

       <h4>Buyer's arrangement with Issuing Bank:</h4>
       <ol>
        <li><p>All Valid Credit / Debit/ Cash Card/ and other payment instruments are processed using a Credit Card payment gateway or appropriate payment system infrastructure and the same will also be governed by the terms and conditions agreed to between the Buyer and the respective Issuing Bank and payment instrument issuing company.</p></li>
        <li><p>All Online Bank Transfers from Valid Bank Accounts are processed using the gateway provided by the respective Issuing Bank which support Payment Facility to provide these services to the Users. All such Online Bank Transfers on Payment Facility are also governed by the terms and conditions agreed to between Buyer and the respective Issuing Bank.</p></li>
       </ol>

       <h4>Digital Content: Credence Ideas</h4>
       <ol>
        <li><p>These Terms of Service (“Terms”) govern your access to and use of Credence Ideas (hereinafter referred to as “Content”). By viewing the Contents you agree to be bound by these Terms. Content posted on the Platform is public and can be viewed by everyone who can see the Page.</p></li>
        <li><p>By hosting the Content on the Platform, Credence is neither guaranteeing nor giving any warranty nor making any representation with respect to the Contents. Credence is neither endorsing the views, products or the Services, nor is it responsible for quality or features of the content displayed on the Platform.</p></li>
        <li><p>Any information on the Platform, whether the content or any other information, have not been verified by Credence, therefore, Credence shall not be responsible for any such content or information. Credence will not bear any obligation or liability if You rely on the Contents.</p></li>
        <li><p>If You choose to view or rely, Credence will neither be a party to nor in any manner concerned with the same nor be liable or responsible for any act or omission of the Content Owner.</p></li>
        <li><p>You hereby acknowledge that the Contents are created and owned by Content Owners who own all the rights including the copyrights in the contents. The Contents are available on the Platform for personal use only and you shall not use it for any commercial, promotional, resale or further distribution purposes.</p></li>
        <li><p>Any use or reliance on any Content or materials obtained by you through the Content is at your own risk. We do not endorse, support, represent or guarantee the completeness, truthfulness, accuracy, or reliability of any Content or communications posted on the Platform or endorse any opinions expressed via the contents. You understand that by using the Platform, you may be exposed to Content that might be offensive, harmful, inaccurate or otherwise inappropriate, or in some cases, postings that have been mislabeled or are otherwise deceptive. All Content is the sole responsibility of the person who originated such Content. Credence may not monitor or control the Content posted on the Platform and, we do not take responsibility for such Content.</p></li>
        <li><p>We reserve the right to remove Content that violates the Terms of Use, including for example, copyright or trademark violations, impersonation, unlawful conduct, or harassment.</p></li>
        <li><p>If you see an offensive, abusive, or any unlawful content on the Platform, you can report it to ideas-support@Credence.com</p></li>
        <li><p>You may find content that offends you or that you simply don’t like, but that doesn’t violate the content guidelines. If that happens, you can unfollow the user who posted it or hide the post</p></li>
        <li><p>Your access to and use of the Services or any Content are at your own risk. You understand and agree that the Services are provided to you on an “AS IS” and “AS AVAILABLE” basis. Credence makes no warranty or representation and disclaim all responsibility and liability for: (i) the completeness, accuracy, availability, timeliness, security or reliability of any Content; (ii) any harm to your computer system, loss of data, or other harm that results from your access to or use of any Content; (iii) the deletion of, or the failure to store or to transmit, any Content and other communications maintained by the Services; and (iv) whether the Services will meet your requirements or be available on an uninterrupted, secure, or error-free basis. No advice or information, whether oral or written, obtained through the Content, will create any warranty or representation not expressly made herein.</p></li>
        <li><p>By using the Services you agree that Credence, its parents, affiliates, related companies, officers, directors, employees, agents representatives, partners and licensors, liability is limited to the maximum extent permissible by Law.</p></li>
        <li><p>We may revise these Terms from time to time.</p></li>
       </ol>

       <h4>Digital Content: Credence Video</h4>
       <ol>
        <li><p>These Terms of Service (“Terms”) govern your access to and use of Credence Video (hereinafter referred to as “Content”). By viewing the Contents you agree to be bound by these Terms. Content posted on the Platform is public and can be viewed by everyone who can see the Page.</p></li>
        <li><p>Use of Credence Services is available only to persons who can form a legally binding contract under the Indian Contract Act, 1872.You must be 18 years of age, to avail the Services. Minors may only use the service under the supervision of an adult.</p></li>
        <li><p>You hereby acknowledge that the Contents are created and owned by Content Owners who own all the rights including the copyrights in the contents. The Contents are available on the Platform for personal and non-commercial use only and you shall not use it for any commercial, promotional, resale, further distribution or any other unauthorized purposes. You agree not to use the service for public performances.</p></li>
        <li><p>You further acknowledge that all the intellectual property rights contained in Credence Original contents are solely owned by Credence. During your Credence membership we grant you a limited, non-exclusive, non-transferable, revocable right to access the CredenceVideo service and view the Content. Except for the foregoing, no right, title or interest shall be transferred to you.</p></li>
        <li><p>We can terminate your account or place your account on hold in order to protect our/Partners interest from an actual, probable or suspected theft or other fraudulent activity.</p></li>
        <li><p>We reserve the right to remove Content that violates the Terms of Use, including for example, copyright or trademark violations, impersonation, unlawful conduct, or harassment.</p></li>
        <li><p>We may use information such as device ID, location or an account email address used with an existing Credence account to determine eligibility and any offers therof.</p></li>
        <li><p>We may share personal information with our other corporate entities and Platform Partners only for the purposes of giving enhanced customer services. You hereby consent to sharing your information with Third parties unless you specifically opt out. Also, your access to the Services may also be occasionally suspended or restricted to allow for repairs, maintenance, or the introduction of new facilities or services at any time without prior notice. We will attempt to limit the frequency and duration of any such suspension or restriction.</p></li>
        <li><p>If you see an offensive, abusive, or any unlawful content on the Platform, you can report it to customer care of Credence.</p></li>
        <li><p>Your access to and use of the Services or any Content are at your own risk. You understand and agree that the Services are provided to you on an “AS IS” and “AS AVAILABLE” basis. Credence makes no warranty or representation and disclaim all responsibility and liability for: (i) the completeness, accuracy, availability, timeliness, security or reliability of any Content; (ii) any harm to your computer system, loss of data, or other harm that results from your access to or use of any Content; (iii) the deletion of, or the failure to store or to transmit, any Content and other communications maintained by the Services; and (iv) whether the Services will meet your requirements or be available on an uninterrupted, secure, or error-free basis. No advice or information, whether oral or written, obtained through the Content, will create any warranty or representation not expressly made herein.</p></li>
        <li><p>By using the Services you agree that Credence, its parents, affiliates, related companies, officers, directors, employees, agents representatives, partners and licensors, liability is limited to the maximum extent permissible by Law</p></li>
        <li><p>You shall indemnify and hold harmless Credence its owner, licensee, affiliates, subsidiaries, group companies, partners (as applicable) and their respective officers, directors, agents, and employees from any claim, demand, or actions including reasonable attorneys' fees made by any third party or penalty imposed due to or arising out of your breach of the ToU, privacy policy and other policies or your violation of any law, rules, regulations or the rights (including infringement of intellectual property rights) of a third party.</p></li>
        <li><p>Governing laws: The ToU shall be governed, interpreted, and construed in accordance with the laws of India. The place of jurisdiction shall exclusively be Guwahati.</p></li>
        <li><p>We may revise these Terms from time to time.</p></li>
       </ol>

       <h4>Applicable Law</h4>
        <p>This site is controlled and operated by Credence and products are sold by respective Sellers. All material on this site, including images, illustrations, audio clips, and video clips, are protected by copyrights, trademarks, and other intellectual property rights. Material on Platform is solely for Your personal, non-commercial use. You must not copy, reproduce, republish, upload, post, transmit or distribute such material in any way, including by email or other electronic means and whether directly or indirectly and You must not assist any other person to do so. Without the prior written consent of the owner, modification of the materials, use of the materials on any other Platform or networked computer environment or use of the materials for any purpose other than personal, non-commercial use is a violation of the copyrights, trademarks, and other proprietary rights, and is prohibited. Any use for which You receive any remuneration, whether in money or otherwise, is a commercial use for the purposes of this clause.</p>
         <h6>Trademark complaint</h6>
        <p>Credence respects the intellectual property of others. In case You feel that Your Trademark has been infringed, You can write to Credence at  <a style="color:blue" href="mailto:infringement@credenceever.com">infringement@credenceever.com</a> or <a style="color:blue" href="http://ss@credenceever.com">ss@credenceever.com</a>.</p>

       <h4>Limitation of Liability</h4>
       <p>IN NO EVENT SHALL CREDENCE BE LIABLE FOR ANY SPECIAL, INCIDENTAL, INDIRECT OR CONSEQUENTIAL DAMAGES OF ANY KIND IN CONNECTION WITH THESE TERMS OF USE, EVEN IF USER HAS BEEN INFORMED IN ADVANCE OF THE POSSIBILITY OF SUCH DAMAGES.</p>
        <h5>Contact Us</h5>
        <p>Please [contact us][] for any questions or comments (including all inquiries unrelated to copyright infringement) regarding this Platform.</p>
        <h5>Grievance officer</h5>
        <p>In accordance with Information Technology Act 2000 and rules made there under and the Consumer Protection (E-Commerce) Rules, 2020, the name and contact details of the Grievance Officer are provided below:</p>
        <p>Mr. Saikul</p>
        <p>CredenceEver LLP,</p>
        <p>#01, Mulagabharu Path, Hatigaon Road, Assam-781006, India</p>
        <h4>contact us</h4>
        <p>Email: <a style="color:blue" href="mailto:grievance.officer@credenceever.com">grievance.officer@credenceever.com</a></p> 
        <p><a href="tel:+917002475754">Phone: 7002475754</a></p>
        <p>Time: Mon - Sat (9:00 - 18:00)</p>

        <h4>POLICIES</h4>
        <h5>Profanity Policy</h5>
        <p>Credence prohibits the use of language that is racist, hateful, sexual or obscene in nature in a public area.</p>
        <p>If a feedback comment; or any communication made between Users on the Platform; or email communication between Users in relation to transactions conducted on Platform contain profanity, please review Our feedback removal policy and submit a request for action/removal.</p>
        <p>Disciplinary action may result in the indefinite suspension of a User's account, temporary suspension, or a formal warning.</p>
        <p>Credence will consider the circumstances of an alleged policy violation and the user's trading records before taking action.</p>
        <p>Violations of this policy may result in a range of actions, including:</p> 
        <ol>
        <li><p>Limits placed on account privileges.</p></li>
        <li><p>Loss of special status</p></li>
        <li><p>Account suspension</p></li>
       </ol>
       <p>Credence shall have the right to delete a product review posted by the customer at its sole discretion, if it is of the opinion that the review contains offensive language as stated above. Further, if Credence is of the opinion that the review unfairly either: (i) causes disadvantage to a product; or (ii) increases the popularity of the product, Credence shall have the right to delete the customer review. Credence shall also, at its sole discretion have the right to blacklist the customer from posting any further customer reviews.</p>

       <h4>Return/Replacement Policy</h4>
       <h5>Return</h5>
       <p>Definition: 'Return' is defined as the action of giving back the item purchased by the Buyer to the Seller on the Credence Platform. Following situations may arise:</p>
       <ol>
        <li><p>Item was defective</p></li>
        <li><p>Item was damaged during the Shipping</p></li>
        <li><p>Products was / were missing</p></li>
        <li><p>Wrong item was sent.</p></li>
       </ol>
       <p>Return could also result in refund of money in most of the cases.</p>

       <h4>Points to be noted:</h4>
       <p>We encourage the Buyer to review the listing before making the purchase decision. In case Buyer orders a wrong item, Buyer shall not be entitled to any return/refund.</p>
       <p>Buyer needs to raise the return request within the return period applicable to the respective product.Once Buyer has raised a return request by contacting Us, Return could result the following:</p>
       <ol>
        <li><p>Replace after shipment collection.</p></li>
        <li><p>Refund after shipment collection </p></li>
        <li><p>On certain select days as specified by Credence (such as 'On Promotion Days') separate policies may be applicable.</p></li>
       </ol>       
       <p>In the event of the acceptance of the return request raised by the Buyer, Buyer will have to return the product and then the refund shall be credited to the Buyers account.</p>
       <p>Further for returns being made by Buyer to the Seller of the product, the following parameters needs to be ensured by the Buyer:</p>

       <table id="customers">
          <tr>
            <th>Category</th>
            <th>Condition</th>
          </tr>
          <tr>
            <td>Clothing and Footwear</td>
            <td>Should be "New & Unworn" (other than for trial)</td>
          </tr>
          <tr>
             <td>Beauty, Perfume, Health & Personal Care</td>
             <td>Should be "New & Unopened"</td>
          </tr>
          <tr>
             <td>Jewellery</td>
             <td>Should be "New" and returned with original packaging</td>
          </tr>
       </table>
       <p>If the product being returned is not in accordance with the above parameters, then Buyer shall not be entitled to any refund of money.</p>

       <h4>Replacement</h4>
       <p>Definition: Replacement is the action or process of replacing something in place of another. A Buyer can request for replacement whenever he is not happy with the item, reason being Damaged in shipping, Defective item, Item(s) missing, wrong item shipped and the like.</p>
       <h5>Points to be noted:</h5>
       <p>Buyer needs to raise the replacement request within the return period applicable to the respective product. Once Buyer has raised a replacement request by contacting Us. Once the replacement request has been raised, the following steps shall be followed:</p>

       <ol>
        <li><p>Buyer is asked for "Reason for Return". Among others, the following are the leading reasons:</p></li>
        <li><p>Shipping was damaged</p></li>
        <li><p>Item was defective</p></li>
        <li><p>Item Dead on Arrival</p></li>
        <li><p>Item(s) were missing</p></li>
        <li><p>Wrong item sent</p></li>
        <li><p>In case of acceptance of the replacement request, Buyer shall be required to return the product and only after return of the product, we shall be obliged to provide the replacement product to the Buyer.</p></li>
       </ol>
       <p>In case the replacement product/s is not available at all, We can provide the refund to the Buyer and Buyer shall be obligated to accept the refund in lieu of replacement. All the product parameters shall be required to be complied with in cases of replacement</p>
       <p>Following products shall not be eligible for return or replacement:</p>
       <p>a. Damages due to misuse of product;</p>
       <p>b. Incidental damage due to malfunctioning of product;</p>
       <p>c. Any consumable item which has been used/installed;</p>
       <p>d. Products with tampered or missing serial/UPC numbers;</p>
       <p>f. Any damage/defect which are not covered under the manufacturer's warranty</p>
       <p>g. Any product that is returned without all original packaging and accessories, including the box, manufacturer's packaging if any, and all other items originally included with the product/s delivered;</p>
       <p>h. Jewellery which is 'made to order' on customer's request</p>
       <p>i. On Clothing and Footwear, qualified sellers accept 7 day exchange subject to the following conditions:</p>
       <p>j. Clothes and footwear are not used (other than for trial), altered, washed, soiled or damaged in any way.</p>
       <p>k. Original tags and packaging should be intact. For items that come in branded packaging, the box should be undamaged.</p>
       <p>l. Returns are not applicable for 'Made to order' jewellery, Innerwear, lingerie, socks, clothing freebies, etc.</p>
       <p>m. Damaged or defective or 'Not as described' products in Lifestyle category (includes clothing, footwear, etc.) are meanwhile covered by the 30 Day Replacement Guarantee. Kindly click here to know the return policy period (Replacement Guarantee) applicable for different categories.</p>
       <p>If Credence has any suspicion or knowledge that any of its buyers and sellers are involved in any activity that is intended to provide claims or information that is false or not genuine, Credence may also, while reserving its rights to initiate civil and/or criminal proceedings against such member buyers and sellers, at its sole discretion, suspend, block, restrict, cancel the Display Name of such buyers and sellers and/or disqualify that user and any related users from availing protection through this program. Customers who have been blocked for any suspicious or fraudulent activity on Credence will not be allowed to return their products.</p>
       <p>Credence reserves its right to initiate civil and/or criminal proceedings against a user who, files a invalid and/or false claims or provides false, incomplete, or misleading information. In addition to the legal proceedings as aforesaid, Credence may at its sole discretion suspend, block, restrict, cancel the Display Name [and its related Display Names] of such user and/or disqualify that user and any related users from availing protection through this program. Any person who, knowingly and with intent to injure, defraud or deceive, files a Fraudulent Complaint containing false, incomplete, or misleading information may be guilty of a criminal offence and will be prosecuted to the fullest extent of the law.</p>
       <p>DRM Specifications: The DRM (Digital Rights Management) enables us to restrict certain permissions. The Credence DRM specifications restrict the following permissions:</p>
       
       <table id="customers">
          <tr>
            <th>Default Restrictions</th>
            <th>Credence Settings</th>
          </tr>
          <tr>
            <td>Printing</td>
            <td>Not Allowed</td>
          </tr>
          <tr>
             <td>Copying</td>
             <td>Not Allowed</td>
          </tr>
          <tr>
             <td>Side-Loading (from one device to other)</td>
             <td>Not Allowed</td>
          </tr>
          <tr>
             <td>e-mailing</td>
             <td>Not Allowed</td>
          </tr>
          <tr>
             <td>Saving Images</td>
             <td>Not Allowed</td>
          </tr>
          <tr>
             <td>Read out aloud</td>
             <td>Not Allowed</td>
          </tr>
          <tr>
             <td>Number of distinct devices for file downloading</td>
             <td>Allowed (Six)</td>
          </tr>
          <tr>
             <td>Social media sharing</td>
             <td>140 word</td>
          </tr> 
       </table>

       <h5>Email Abuse & Threat Policy</h5>
       <p>Private communication, including email correspondence, is not regulated by Credence. Credence encourages its Users to be professional, courteous and respectful when communicating by email.</p>
       <p>However, Credence will investigate and can take action on certain types of unwanted emails that violate Credence policies.</p>
       <h5>Such instances:</h5>
       <p>Threats of Bodily Harm - Credence does not permit Users to send explicit threats of bodily harm.</p>
       <p>Misuse of Credence System - Credence allows Users to facilitate transactions through the Credencesystem but will investigate any misuse of this service.</p>
       <p>Spoof (Fake) email - Credence will never ask you to provide sensitive information through email. In case you receive any spoof (fake) email, you are requested to report the same to Us through 'Contact Us' tab.</p>
       <p>Spam (Unsolicited Commercial email) - Credence's spam policy applies only to unsolicited commercial messages sent by Credence Users. Credence Users are not allowed to send spam messages to other Users.</p>
       <p>Offers to Buy or Sell Outside of Credence - Credence prohibits email offers to buy or sell listed products outside of the Credence Platform. Offers of this nature are a potential fraud risk.</p>
       <p>Credence policy prohibits user-to-user threats of physical harm via any method including, phone, email and on Our public message boards.</p>

       <p>Violations of this policy may result in a range of actions, including:</p>
       <ul>
          <li>Limits on account privileges</li>
          <li>Account suspension</li>
          <li>Cancellation of listings</li>
          <li>Loss of special status</li>
       </ul>

          <h5>Mr. Saikul</h5>
          <h5>CredenceEver LLP,</h5>
          <h5>#01,Mulagabharu Path,</h5>
          <h5>HatigaonRoad,Guwahati, Assam-781006,India</h5>
          <h5>contact us</h5>
          <p>Email: <a style="color:blue" href="mailto:grievance.officer@credenceever.com">grievance.officer@credenceever.com</a></p> 
          <p><a href="tel:+917002475754">Phone: 7002475754</a></p>
          <p>Time: Mon - Sat (9:00 - 18:00)</p>
    </div>
</section>



     
@endsection

@section('script')
@endsection